### ISSUE TITLE
Image Size and SPIFFS Wearout

### ISSUE THREAD

**Issue by ispybadguys** [Samox1/ESP_Thermal_Camera_WebServer#2]
I love your application here. And you code looks great. Very clear and well organized. Two questions The image on the web page is too late to fit without scrolling. Is there a way to reduce this?

Have you had any problems with wearing out the SPIFFS with continuous writing?

Thanks

Kurt

**Comment by Samox1** [comment]
Sorry for not responding - I will try to reduce latency (will note that in my TODO list)

"Have you had any problems with wearing out the SPIFFS with continuous writing?" 
For now, only for testing, I don't have any problems with SPIFFS - I think I don't use SPIFFS too much to talk about durability
