### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by JatinJani** [Samox1/ESP_Thermal_Camera_WebServer#3]
Hello I am new to all this. I have an ESP8266 NodeMCU and MLX90640. It is connected as below : 
3.3v 
GND
D5 (SDA)
D4(SDL)

Can you please help and tell me how to proceed and get the image to display on a WebServer ? 

Much appreciated. 

Thanks.

**Comment by Samox1** [comment]
Sorry for not responding... Hope you found a solution!

**Comment by oficjalniebktv** [comment]
Udało wam się odszukać poprawny kod który dobrze działa z ESP8266 NodeMCU i MLX90640

**Comment by Samox1** [comment]
Jeśli to jest pytanie - to na ten moment mam w planach dostosowanie kodu do nowych bibliotek i sprawdzenie działania na Arduino IDE 2.X (na ten moment 2.3.1), ale z powodu pracy i innych projektów, ten projekt jest rozłożony w czasie

**Comment by oficjalniebktv** [comment]
Okey , dziękuje za odpowiedź 
W dniu 2024-02-15 10:39:49 użytkownik Szymon Baczyński ***@***.***> napisał:
 
Jeśli to jest pytanie - to na ten moment mam w planach dostosowanie kodu do nowych bibliotek i sprawdzenie działania na Arduino IDE 2.X (na ten moment 2.3.1), ale z powodu pracy i innych projektów, ten projekt jest rozłożony w czasie

**Comment by oficjalniebktv** [comment]
okey dzięki za odpowiedź
